name: build
on: pull_request

jobs:
  noetic_build:
    runs-on:  ubuntu-20.04

    container: ros:noetic
    services:
      ros:
        image: ros

    defaults:
      run:
        shell: bash

    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: rosdep update
        run: |
          apt-get update
          rosdep update

      - name: Create Workspace
        run: |
          mkdir -p ~/eagleye/src/
          cp -r `pwd` ~/eagleye/src/

      - name: Clone submodules
        run: |
          cd ~/eagleye/src/
          apt-get install git -y
          git clone https://github.com/MapIV/rtklib_ros_bridge.git
          git clone https://github.com/MapIV/kml_generator
          git clone https://github.com/MapIV/multi_rosbag_controller.git
          git clone https://github.com/MapIV/llh_converter.git
          cd llh_converter
          git checkout 405fe659f0cead637a1c4c8ef4d8c72f9cb194c4
          cd ..
          git clone https://github.com/MapIV/gnss_compass_ros.git

      - name: Install GeographicLib
        run: |
          apt-get install -y libgeographic-dev geographiclib-tools geographiclib-doc

      - name: Build
        run: |
          cd ~/eagleye/
          source /opt/ros/noetic/setup.bash
          rosdep install --from-paths src --ignore-src -r -y
          catkin_make -DCMAKE_BUILD_TYPE=Release -j2
